### ISSUE TITLE
Last commit : Sep 3, 2015

### ISSUE THREAD

**Issue by extremeshok** [baruwaproject/baruwa2#100]
Please can you commit the changes/fixes, which were done in the passed year

thanks

**Comment by akissa** [comment]
http://baruwa-users-list.963389.n3.nabble.com/Baruwa-Community-Edition-End-of-Life-and-End-of-Support-td4027756.html

**Comment by extremeshok** [comment]
Btw i did respond to the request for maintainer.

Could you upload the commits as of may 2016 ?

**Comment by akissa** [comment]
The code bases diverged a long time a go, i have way too little time at the moment to port features to the community edition. The community edition is dead and buried.
