### ISSUE TITLE
[Enhancement] Perform connection check from the actual mail-node

### ISSUE THREAD

**Issue by rmoesbergen** [baruwaproject/baruwa2#104]
When performing an SMTP connection check for a delivery server, the check is done from web-server. This leads to false failures because the webserver don't have SMTP access (in fact, in our setup they are in a completely different network). It would be more accurate to perform the connection check from the real SMTP mail node, instead of the webserver. Is this possible to change?

**Comment by akissa** [comment]
Fixed, will be in the next update
