### ISSUE TITLE
Managed Rolling Updates

### ISSUE THREAD

**Issue by OneiricIT** [baruwaproject/baruwa2#117]
Would be great to see controlled rolling updates of nodes when new packages are available via management page instead of having to jump on each to perform updates and reboot (if desired / required). 

- Performs 'baruwa-setup -s' on one node at a time, and awaits successful update and minute difference before proceeding with next. Updates performed based on order of roles in recommended update order i.e. DB backend > Mail > Web etc
- Option to cancel update of further nodes if required in instance needs to be stopped.
- Live status of process shown i.e. running log with console like message
- Option to select to restart each node after update, which system waits for successful reconnect prior to continuing
- Would invoke backup of each node prior to performing the backup. If backup fails, then stop process. Have tick-box option to continue on backup failures

Would be good to see other options or suggestions.

**Comment by akissa** [comment]
I do not think much of the above is possible, this the reason why most people have staging and production environments, You need to run updates through staging before promoting to production.

**Comment by OneiricIT** [comment]
OK - worth a query. Would just ease administration and safe guard / standardise update procedure.
