### ISSUE TITLE
NRPE mailq check and mailq command always return no items

### ISSUE THREAD

**Issue by rmoesbergen** [baruwaproject/baruwa2#119]
It seems that after the update to 2.1.4, the mailq command no longer displays the actual incoming mail queue. Probably because the 'real' queue has moved to /var/spool/exim.in/baruwa/input, instead of /var/spool/exim.in/input, where mailq checks. This also means that the NRPE / monitoring check is not working, which is a problem. Can this be fixed?

**Comment by tomtakan** [comment]
Please manually change that, we have fixed it for the next pkg update.

**Comment by rmoesbergen** [comment]
Okay. Where can I fix the path? In /etc/exim/exim.conf, setting spool_directory?

**Comment by akissa** [comment]
No, hold that thought, this requires further investigation.

**Comment by akissa** [comment]
Created a new nrpe plugin to address this, will be part of BaruwaOS 6.9
