### ISSUE TITLE
Web GUI Login issue (internal server errror)

### ISSUE THREAD

**Issue by rmoesbergen** [baruwaproject/baruwa2#122]
Every time a user logs in, they get a 500 internal server error. The logs say:

Apr  5 09:28:46 lnx2630vm uwsgi: Error - <type 'exceptions.UnboundLocalError'>: local variable 'doms' referenced before assignment
Apr  5 09:28:46 lnx2630vm uwsgi: URL: https://mail-admin.solvinity.com/accounts/loggedin?came_from=%2F#012File '/usr/lib/python2.6/site-packages/weberror/errormiddleware.py', line 162 in __call__#012  app_iter = self.application(environ, sr_checker)#012File '/usr/lib/python2.6/site-packages/beaker/middleware.py', line 155 in __call__#012  return self.wrap_app(environ, session_start_response)#012File '/usr/lib/python2.6/site-packages/repoze/who/middleware.py', line 107 in __call__#012  app_iter = app(environ, wrapper.wrap_start_response)#012File '/usr/lib/python2.6/site-packages/routes/middleware.py', line 131 in __call__#012  response = self.app(environ, start_response)#012File '/usr/lib/python2.6/site-packages/pylons/wsgiapp.py', line 103 in __call__#012  response = self.dispatch(controller, environ, start_response)#012File '/usr/lib/python2.6/site-packages/pylons/wsgiapp.py', line 313 in dispatch#012  return controller(environ, start_response)#012File '/usr/lib64/python2.6/site-packages/baruwa/lib/base.py', line 110 in __call__#012  return WSGIController.__call__(self, environ, start_response)#012File '/usr/lib/python2.6/site-packages/pylons/controllers/core.py', line 214 in __call__#012  response = self._dispatch_call()#012File '/usr/lib/python2.6/site-packages/pylons/controllers/core.py', line 164 in _dispatch_call#012  response = self._inspect_call(func)#012File '/usr/lib/python2.6/site-packages/pylons/controllers/core.py', line 107 in _inspect_call#012  result = self._perform_call(func, args)#012File '/usr/lib/python2.6/site-packages/pylons/controllers/core.py', line 57 in _perform_call#012  return func(**args)#012File '/usr/lib64/python2.6/site-packages/baruwa/controllers/accounts.py', line 176 in loggedin#012  user, local_part, domain, domains, self.identity)#012File '/usr/lib64/python2.6/site-packages/baruwa/lib/db/__init__.py', line 859 in user_address_update#012  mailattr.split('@')[1] in doms):#012UnboundLocalError: local variable 'doms' referenced before assignment#012#012#012CGI Variables#012----------

Any idea what causes this?

**Comment by akissa** [comment]
The user is not assigned to a domain. You need to assign them to atleast one domain

**Comment by akissa** [comment]
Fix for the exception in the next release.
