### ISSUE TITLE
Bug: Tidydb does not run on callout and retry databases for exim.in

### ISSUE THREAD

**Issue by rmoesbergen** [baruwaproject/baruwa2#126]
In /etc/cron.daily/exim/tidydb, the spooldir is set to /var/spool/exim. However, the incoming exim MTA uses /var/spool/exim.in. This causes the retry and callout db's not to be tidied and grow very large (160MB in my case). Please fix so the exim.in/db/* databases are tidied as well.

#!/bin/bash

SPOOLDIR=/var/spool/exim

cd $SPOOLDIR/db
for a in retry misc wait-* callout ratelimit; do
    [ -r "$a" ] || continue
    [ "${a%%.lockfile}" = "$a" ] || continue
    /usr/sbin/exim_tidydb $SPOOLDIR $a >/dev/null
done

**Comment by akissa** [comment]
This is a regression the used to be cleaned up by /etc/cron.hourly/baruwa

**Comment by rmoesbergen** [comment]
Could it be that this causes verification false negatives? I'm getting a lot of calls / reports of cases where the backend server accepts an address just fine, but baruwa returns a 'address does not exist'.

**Comment by akissa** [comment]
I do not think so, it is most likely the UTF8SMTP causing the issue. You need to apply the fix in the release notes.

https://www.baruwa.com/docs/guide/admin/releasenotes/6.9.html#mail-log-entries-containing-utf8-support-required-but-not-offered-for-forwarding

**Comment by rmoesbergen** [comment]
I've already implemented that fix since we upgraded. And, when I manually purge the callout database, things start working again and mail is accepted.

**Comment by akissa** [comment]
The question to investigate is why is a negative response being cached in the first place ? Is the destination responding intermitently as in alternating between yes and no ? There has to be a no response from the destination for that to get cached

**Comment by akissa** [comment]
Updated rpms pushed and contain script functionality to cleanup both queues
