### ISSUE TITLE
Feature request: 7zip support in MailScanner

### ISSUE THREAD

**Issue by rmoesbergen** [baruwaproject/baruwa2#133]
A few days ago a patch was committed to MailScanner, teaching it how to use 7zip to look into archives other than .zip and .rar. Please add this feature to baruwa, so archive content policy's work on .7z and lots of other archive formats.

https://github.com/MailScanner/v5/commit/bf67a0fa0bf3f260e3aaeea5885d678533bc3e20

**Comment by akissa** [comment]
We have this on our roadmap, we will use a different implementation however not the command line based approach they have used.

**Comment by akissa** [comment]
Implemented.
