### ISSUE TITLE
Missing monitoring check

### ISSUE THREAD

**Issue by rmoesbergen** [baruwaproject/baruwa2#142]
Hi,

We had a few cases recently where the 'fabio' process stopped working, and prevented connections to the backend database from working. Is it possible to add an 'nrpe' check for this process? There's supposedly a /health endpoint (running @ http://127.0.0.1:9998/health) that might be useful for this.

We're still investigating why it stopped working, will let you know once we find out.

**Comment by akissa** [comment]
Added monitoring of the process on frontend systems.
