### ISSUE TITLE
Return sub-string results in search

### ISSUE THREAD

**Issue by isgsoftware** [baruwaproject/baruwa2#145]
When searching lists such as domains or organizations, only full word matches are returned.  It would be great if substring matches could also be returned.  Since the lists are not sorted by name, finding entries when there are many is difficult.

**Comment by akissa** [comment]
Have you tried enabling wildcard matches in `baruwa-setup` then searching using wildcards such as `*mail*`

**Comment by isgsoftware** [comment]
I will double check. I thought I had that feature on and maybe it's not because I did try using * and also tried escaping it as well and returned 0 results.

**Comment by akissa** [comment]
`*mail*` should match `gmail.com`, `hotmail.com` etc No need to escape anything.

**Comment by akissa** [comment]
What is the status on this @isgsoftware

**Comment by isgsoftware** [comment]
Hello, 
I think this is resolved. You can close it out. Thanks for following up & sorry I didn't provide an update. 
gary

**Comment by akissa** [comment]
Thanks
