### ISSUE TITLE
[Feature] Suppress 'OK' dialog box in baruwa-setup with -s option

### ISSUE THREAD

**Issue by rmoesbergen** [baruwaproject/baruwa2#146]
When running baruwa-setup -s (silent / non interactive), every step is performed without user interaction, except the last one: a dialog box showing 'The setup is complete' -> [OK]. This makes it unusable for inclusion in scripting. Can this dialog be disabled when the -s option is passed to baruwa-setup?

**Comment by akissa** [comment]
Implemented, will be in the next update, the options are `-n` and `--non-interactive`

**Comment by rmoesbergen** [comment]
Wow, that was fast :) Thanks!

**Comment by akissa** [comment]
The update has been released - https://packages.baruwa.com/baruwa-setup.html

**Comment by rmoesbergen** [comment]
tested and works like a charm, thanks!
