### ISSUE TITLE
Disable pgbounce connection logging to prevent /var/ from filling up

### ISSUE THREAD

**Issue by rmoesbergen** [baruwaproject/baruwa2#147]
I have a 'post install' script that disables pgbouncer logging because it fills up the /var partition with logging, when a lot of e-mail is processed. The logging itself is not particularly useful. Would it be possible to disable these 2 settings by default in pgbouncer.ini?

# pgbouncer.ini:
; log if client connects or server connection is made
log_connections = 0

; log if and why connection was closed
log_disconnections = 0

**Comment by akissa** [comment]
Done. Queued for testing, will be in the next update.

**Comment by rmoesbergen** [comment]
Awesome, thanks!

**Comment by rmoesbergen** [comment]
works!
