### ISSUE TITLE
Domain Templates

### ISSUE THREAD

**Issue by MACscr** [baruwaproject/baruwa2#24]
I pretty much want/need the exact same settings for every domain I add to Baruwa. Is there any way to set any defaults, etc? Its very frustrating have to fill out the same things every single time I add a domain. Especially since I have a bunch to add initially. Even the smtp servers are the same same (well they are when I'm doing batches of domains). =/

**Comment by mijnsleutel** [comment]
What about using the api ? We created all domains with the api in one go. Now all new domains added automatic with the same api scripts.

**Comment by akissa** [comment]
The API and the new YAML import system do provide mass import functionality now so closing this.
