### ISSUE TITLE
[Feature request] - importing/exporting users with multiple aliases from/to a csv file

### ISSUE THREAD

**Issue by ajendoubi** [baruwaproject/baruwa2#34]
Hi,
The current situation with importing or exporting users from CSV file is that when exporting only one alias will be exported by baruwa instead of all of them (if more than 1 alias is included in the user profile), same for importing from csv file where you can only put 1 alias in the address field, otherwise the import will fail.
Thanks,
A.J.

**Comment by akissa** [comment]
Fixed by converting to YAML
