### ISSUE TITLE
[bug?] - importing users from csv file does not create them

### ISSUE THREAD

**Issue by ajendoubi** [baruwaproject/baruwa2#35]
Hi,
I did an export of users already present in our baruwa system to a csv file from the export button in the interface, I took that file as a template and modified it in a text editor (not even using an MS Excel to edit the file)...
After uploading the file, no user is imported or created, the uploaded file sit in /var/lib/baruwa/data/uploads and nothing is happening.... just to let know that I just used one row and modified the username, and his email address to not match with anything else already present in our baruwa system... I didn't change the format, neither put any password as the export just provided an empty filed in the password. I used google chrome to do this process of export and import.
I think this could be a bug, unless someone can provide a working csv file as template to import and I can test our system with that to confirm.
Thanks,
A.J.

**Comment by akissa** [comment]
Fixed by converting imports to YAML
