### ISSUE TITLE
API Suggestion

### ISSUE THREAD

**Issue by mijnsleutel** [baruwaproject/baruwa2#72]
Most of the api commands rely on domain_id. To get the ID of the domain we can do two things. When add a domain, keep the ID in response saved somewhere else, ore use the list all domains to find the ID. The list all domains is a response with if you have many results a pitty one to work with. You have to  use the navigation in the response to get domains for page 2 , 3 ,4  etc etc. Quiet big process just to get an ID.

Suggestion
one simple API command where u can put in domainname. With ID response. And offcourse only the ID if that domain belongs to that user.

**Comment by akissa** [comment]
Implemented will be released in 2.1.2
