### ISSUE TITLE
[bug] message list search

### ISSUE THREAD

**Issue by mijnsleutel** [baruwaproject/baruwa2#73]
When we use the search on the full message list, the result is not 100% sorted by date.

Some recent mails appear between very old mail. It makes it difficult to find quick a mail back.

Also it would be a nice addition to put filter and sort on the columns.

**Comment by akissa** [comment]
You you want a specific message, you should not be using the search function. You need to use the filters instead to find specific messages.

**Comment by mijnsleutel** [comment]
Hi Andrew,


Not a specifici message, but all messages to a specific adres.


The left column with dates is not sorting 100% correct.


If needed, can make a screenshot for you


-Mike



 Van:   Andrew Colin Kissa <notifications@github.com> 
 Aan:   baruwaproject/baruwa2 <baruwa2@noreply.github.com> 
 Cc:   mijnsleutel <m.hoffs@mijn-sleutel.com> 
 Verzonden:   5-4-2016 13:08 
 Onderwerp:   Re: [baruwaproject/baruwa2] [bug] message list search (#73) 


You you want a specific message, you should not be using the search function. You need to use the filters instead to find specific messages.

**Comment by akissa** [comment]
At the moment it is not possible to sort by date, in a future version where it is possible we will support that

**Comment by akissa** [comment]
Implemented.
