### ISSUE TITLE
Feature Request: language settings

### ISSUE THREAD

**Issue by mijnsleutel** [baruwaproject/baruwa2#75]
The current panel autodectect language settings. The dutch translation is far from perfect. What about option in account, if set then it choose that language, if not set auto detect.

**Comment by akissa** [comment]
This is already possible check for baruwa.languages in /etc/baruwa/production.ini you can set the language(s) you want there. Implemented in 2.0.6 https://www.baruwa.com/docs/guide/admin/changelog.html#change-2-0-6
