### ISSUE TITLE
New feature: blocking policy information

### ISSUE THREAD

**Issue by mijnsleutel** [baruwaproject/baruwa2#76]
Hi, 

We have some customers that hit the default content protection policy for files. If we look at the log line where it shows protected, there is no easy way to see which policy produced that deny. Maybe after the infected Y, show the regular expression that did actual trigger that deny.

-TY

**Comment by akissa** [comment]
Am not sure i understand the request fully, can you please post a log extract

**Comment by mijnsleutel** [comment]
We have mailes that are marked as infected due file policies. But in the details we cannot easy see which rule did actually trigger the mail. It is marked as infected, and no more information.

**Comment by mijnsleutel** [comment]
for example, email with attachment: p16-02141.zip got marked as infected. But what rule did actually marked that one as infected. The content inside is regular valid content.

**Comment by akissa** [comment]
Implemented, will be part of the next update
