### ISSUE TITLE
Feature request: Implement generation/sending of DMARC feedback reports

### ISSUE THREAD

**Issue by rmoesbergen** [baruwaproject/baruwa2#77]
I would like to request a feature to be implemented in Baruwa Enterprise. Please consider implementing RFC 7489, chapter 7: DMARC Aggregate Feedback reports. When implemented, Baruwa would gather statistics for every sender and create and send the DMARC reports the sender requests in their DMARC DNS record(s)

**Comment by akissa** [comment]
Done will be part of next update
