### ISSUE TITLE
Feature request: Allow mail for a domain to be 'blackhole' routed

### ISSUE THREAD

**Issue by rmoesbergen** [baruwaproject/baruwa2#78]
We have several domains that receive e-mail, but that we want to be 'blackhole routed', a.k.a. deleted, sometimes temporarily. It would be nice to have a way to specify under 'delivery servers', that mail should not be delivered, but deleted upon arrival.

**Comment by akissa** [comment]
Does this have to be within the interface as you can already perform this using the customization hooks

**Comment by rmoesbergen** [comment]
Thanks for your response. I'm requesting it for the GUI, because we have 20+ admins that are not all familiar with the exim configuration syntax. Also, we'll be deploying a lot of mailservers, for which this configuration would have to be manually synced between them.

**Comment by akissa** [comment]
After considering this issue i think it is better to have this implemented as a setting on the domain itself unless you have a compeling reason as to why you want it in the delivery servers

**Comment by akissa** [comment]
Also should the mail be discarded before it is processed or discarded after it has been processed and logged ?.

**Comment by extremeshok** [comment]
+1 for under domains. 

Could we have both discard and process and discard options set via a selector ?

**Comment by rmoesbergen** [comment]
As an option on the domain is fine with me, makes more sense indeed.

I prefer that everything is logged, including stuff that will be deleted. At least we can report / see what's going on and nothing vanishes without a trace.

**Comment by akissa** [comment]
Implemented, will be part of the next update
