### ISSUE TITLE
[bug] disable junkemailfilter result in Could not complete sender verify

### ISSUE THREAD

**Issue by mijnsleutel** [baruwaproject/baruwa2#80]
Hi,

After disabling junkemailfilter with baruwa-setup, the last 3 days all email got bounced with in the logfile: Could not complete sender verify

**Comment by akissa** [comment]
The two are not related, the issue is probabely caused by DNS resolution not working on your system possibly due to a network firewall blocking/ratelimiting queries from the system. Contact support if you require assistance debugging the issue

**Comment by mijnsleutel** [comment]
100% sure no dns problem. Just reactivated the rbl and mail start working again.

**Comment by akissa** [comment]
The RBL check has got nothing to do with Sender verification. Sender verification will only fail if the domain cannot be resolved.

**Comment by mijnsleutel** [comment]
[root@mail1 log]# cat /etc/resolv.conf
# Generated by NetworkManager
search gateway.****
nameserver 127.0.0.1
[root@mail1 log]# ping github.com
PING github.com (192.30.252.128) 56(84) bytes of data.
64 bytes from github.com (192.30.252.128): icmp_seq=1 ttl=53 time=88.0 ms
^C
--- github.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 713ms
rtt min/avg/max/mdev = 88.080/88.080/88.080/0.000 ms
[root@mail1 log]# ping baruwa.com
PING baruwa.com (84.200.48.198) 56(84) bytes of data.
64 bytes from www.baruwa.com (84.200.48.198): icmp_seq=1 ttl=57 time=23.1 ms
^C
--- baruwa.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 797ms
rtt min/avg/max/mdev = 23.113/23.113/23.113/0.000 ms

**Comment by akissa** [comment]
What is the full rejection message you get including the url that is generated to the help page ?

**Comment by mijnsleutel** [comment]
At the moment, mail is accepted, and get stuck in the server.

**Comment by extremeshok** [comment]
Check of your baruwa ips are not on any rbls

**Comment by akissa** [comment]
@mijnsleutel This is not a bug please contact support such that we can work through your issue.

**Comment by mijnsleutel** [comment]
we use a pool of ips, to level the reputation. At the AS abuse zero abused messages, and so far first 2 checked, not listed
