### ISSUE TITLE
Feature Request: create user accounts automatically if not existed

### ISSUE THREAD

**Issue by si458** [baruwaproject/baruwa2#81]
Hi,

customer A with 6 email accounts signs up for mailcleaning, all cleaning fine and working correctly,

however each email account isnt getting there reports only the admin email account of the server gets the reports

it appears the email account has to login to the mailcleaner at least ONCE for the server to create an account to then send reports to that user each day

could the server possible, if the account doesnt exist, create the user automatically, which would then allow the user to get the reports automatically every day

Simon

**Comment by extremeshok** [comment]
+1 this would be a nice addition
__________________________________.    https://eXtremeSHOK.com     .__________________________________

**Comment by akissa** [comment]
Will not create an account simply based on an email address, will however send a quarantine report to any address that has valid delivery and has over 5 messages in the quarantine.

This feature will need to be turned on via a configuration switch.

**Comment by extremeshok** [comment]
Yeah exactly like that

__________________________________.    https://eXtremeSHOK.com     .__________________________________

**Comment by si458** [comment]
Sounds like a wonderful idea!

Is it possible for a value for the min number in quarantine to send an email? 

So if a user has 1 or 10 emails then send a report

:)
