### ISSUE TITLE
[bug] Dmarc report generation fails

### ISSUE THREAD

**Issue by rmoesbergen** [baruwaproject/baruwa2#86]
Today I got the errors below in my inbox. We have 'enable dmarc reports' enabled. I don't see outbound mails for these domains, so the reports are not sent. Bug?

-----------------------
/etc/cron.daily/baruwa-dmarc:

Use of uninitialized value $answer in scalar chomp at /usr/bin/baruwa-dmarcreports line 890.
Use of uninitialized value $answer in concatenation (.) or string at /usr/bin/baruwa-dmarcreports line 891.
baruwa-dmarcreports: failed to send report for ing.nl to Global.Mail.DMARC@ing.net ()
Use of uninitialized value $answer in scalar chomp at /usr/bin/baruwa-dmarcreports line 890.
Use of uninitialized value $answer in concatenation (.) or string at /usr/bin/baruwa-dmarcreports line 891.
baruwa-dmarcreports: failed to send report for ing.nl to ejdvezzq@ag.dmarcian-eu.com ()
Use of uninitialized value $answer in scalar chomp at /usr/bin/baruwa-dmarcreports line 890.
Use of uninitialized value $answer in concatenation (.) or string at /usr/bin/baruwa-dmarcreports line 891.
baruwa-dmarcreports: failed to send report for ing.nl to dmarc.feedback@ing.nl ()
Use of uninitialized value $answer in scalar chomp at /usr/bin/baruwa-dmarcreports line 890.
Use of uninitialized value $answer in concatenation (.) or string at /usr/bin/baruwa-dmarcreports line 891.
baruwa-dmarcreports: failed to send report for nl.pwc.com to dmarc_admins@pwc.com ()
Use of uninitialized value $answer in scalar chomp at /usr/bin/baruwa-dmarcreports line 890.
Use of uninitialized value $answer in concatenation (.) or string at /usr/bin/baruwa-dmarcreports line 891.
baruwa-dmarcreports: failed to send report for icscards.nl to dmarcreport@icscards.nl ()
Use of uninitialized value $answer in scalar chomp at /usr/bin/baruwa-dmarcreports line 890.
Use of uninitialized value $answer in concatenation (.) or string at /usr/bin/baruwa-dmarcreports line 891.
baruwa-dmarcreports: failed to send report for outlook.com to d@rua.agari.com ()
Use of uninitialized value $answer in scalar chomp at /usr/bin/baruwa-dmarcreports line 890.
Use of uninitialized value $answer in concatenation (.) or string at /usr/bin/baruwa-dmarcreports line 891.
baruwa-dmarcreports: failed to send report for outlook.com to dmarc_agg@auth.returnpath.net ()
Use of uninitialized value $answer in scalar chomp at /usr/bin/baruwa-dmarcreports line 890.
Use of uninitialized value $answer in concatenation (.) or string at /usr/bin/baruwa-dmarcreports line 891.
baruwa-dmarcreports: failed to send report for dji.minjus.nl to dmarc-test@minvenj.nl ()
Use of uninitialized value $answer in scalar chomp at /usr/bin/baruwa-dmarcreports line 890.
Use of uninitialized value $answer in concatenation (.) or string at /usr/bin/baruwa-dmarcreports line 891.
baruwa-dmarcreports: failed to send report for minvenj.nl to dmarc-test@minvenj.nl ()
Use of uninitialized value $answer in scalar chomp at /usr/bin/baruwa-dmarcreports line 890.
Use of uninitialized value $answer in concatenation (.) or string at /usr/bin/baruwa-dmarcreports line 891.
baruwa-dmarcreports: failed to send report for axians.com to dmarc@vinci-energies.com ()
Use of uninitialized value $answer in scalar chomp at /usr/bin/baruwa-dmarcreports line 890.
Use of uninitialized value $answer in concatenation (.) or string at /usr/bin/baruwa-dmarcreports line 891.
baruwa-dmarcreports: failed to send report for nl.abnamro.com to dmarc@nl.abnamro.com ()
Use of uninitialized value $answer in scalar chomp at /usr/bin/baruwa-dmarcreports line 890.
Use of uninitialized value $answer in concatenation (.) or string at /usr/bin/baruwa-dmarcreports line 891.
baruwa-dmarcreports: failed to send report for rabobank.nl to dmarc.feedback@rabobank.nl ()
Use of uninitialized value $answer in scalar chomp at /usr/bin/baruwa-dmarcreports line 890.
Use of uninitialized value $answer in concatenation (.) or string at /usr/bin/baruwa-dmarcreports line 891.
baruwa-dmarcreports: failed to send report for rechtspraak.nl to dmarc-test@minvenj.nl ()
Use of uninitialized value $answer in scalar chomp at /usr/bin/baruwa-dmarcreports line 890.
Use of uninitialized value $answer in concatenation (.) or string at /usr/bin/baruwa-dmarcreports line 891.
baruwa-dmarcreports: failed to send report for ind.minvenj.nl to dmarc-test@minvenj.nl ()
Use of uninitialized value $answer in scalar chomp at /usr/bin/baruwa-dmarcreports line 890.
Use of uninitialized value $answer in concatenation (.) or string at /usr/bin/baruwa-dmarcreports line 891.
baruwa-dmarcreports: failed to send report for securelink.nl to dmarc-reports@securelink.nl ()
Use of uninitialized value $answer in scalar chomp at /usr/bin/baruwa-dmarcreports line 890.
Use of uninitialized value $answer in concatenation (.) or string at /usr/bin/baruwa-dmarcreports line 891.
baruwa-dmarcreports: failed to send report for ahold.com to ahold.dmarc.group@ahold.com ()
Use of uninitialized value $answer in scalar chomp at /usr/bin/baruwa-dmarcreports line 890.
Use of uninitialized value $answer in concatenation (.) or string at /usr/bin/baruwa-dmarcreports line 891.
baruwa-dmarcreports: failed to send report for hotmail.com to d@rua.agari.com ()
Use of uninitialized value $answer in scalar chomp at /usr/bin/baruwa-dmarcreports line 890.
Use of uninitialized value $answer in concatenation (.) or string at /usr/bin/baruwa-dmarcreports line 891.
baruwa-dmarcreports: failed to send report for gdi.minvenj.nl to dmarc-test@minvenj.nl ()
Use of uninitialized value $answer in scalar chomp at /usr/bin/baruwa-dmarcreports line 890.
Use of uninitialized value $answer in concatenation (.) or string at /usr/bin/baruwa-dmarcreports line 891.
baruwa-dmarcreports: failed to send report for infor.com to dmarc-rua@infor.com ()
Use of uninitialized value $answer in scalar chomp at /usr/bin/baruwa-dmarcreports line 890.
Use of uninitialized value $answer in concatenation (.) or string at /usr/bin/baruwa-dmarcreports line 891.
baruwa-dmarcreports: failed to send report for go.surveymonkey.com to dmarc_agg@auth.returnpath.net ()
Use of uninitialized value $answer in scalar chomp at /usr/bin/baruwa-dmarcreports line 890.
Use of uninitialized value $answer in concatenation (.) or string at /usr/bin/baruwa-dmarcreports line 891.
baruwa-dmarcreports: failed to send report for bol.com to svcqy6gf@ag.dmarcian.com ()

**Comment by tomtakan** [comment]
Hi
Was this a once off or it is happening every day ?

**Comment by rmoesbergen** [comment]
I get an e-mail like this every day, and dmarc reports do not seem to be sent out.

**Comment by tomtakan** [comment]
The error indicates that the SMTP conversation to send the message failed. Could you please provide us with extracts from the MTA log to determine what the issue is.

**Comment by rmoesbergen** [comment]
I see lines like this:

2016-07-13 08:53:09 1bN8up-0003A0-8W H=mx2.ag.measuremail.com [195.137.215.234]: SMTP error from remote mail server after RCPT TO:<dmarc.feedback@ag.measuremail.com>: 452 4.2.2 Mailbox full

2016-07-13 03:24:56 1bN8un-0003A0-99 H=mail.measuremail.com [194.120.47.234]: SMTP error from remote mail server after RCPT TO:<dmarc.feedback@measuremail.com>: 451 4.7.1 Temporarily rejected. Try again later.

So whenever delivery to a dmarc report recipient address fails, an error mail is produced. Since we do not control these recipient adresses (they are specified in DMARC DNS records), I suggest these are ignored, instead of mailed to the admin every day.

**Comment by akissa** [comment]
Hi can you check if the latest update resolved this issue.

**Comment by rmoesbergen** [comment]
I now get this:

baruwa-dmarcexpire: DELETE failed: ERROR:  update or delete on table "dmarc_messages" violates foreign key constraint "dmarc_signatures_message_fkey" on table "dmarc_signatures"
DETAIL:  Key (id)=(1) is still referenced from table "dmarc_signatures".

Which is probably unrelated, but prevents me from testing if the solution worked :(

**Comment by akissa** [comment]
As far as i know the reports are sent out, the error above is not from baruwa-dmarcreport it is baruwa-dmarcexpire, which is the cleanup script.

**Comment by rmoesbergen** [comment]
Ah, yes, correct. So this issue fixed. I'll create another one for the expire issue.
