### ISSUE TITLE
Feature request: Allow an external users to be promoted to 'Domain Admin' via the GUI

### ISSUE THREAD

**Issue by rmoesbergen** [baruwaproject/baruwa2#88]
Currently, the type of en externally authenticated user cannot be changed. However, sometimes we want an external user to be domain admin for their organization. We then have to delete the account, and re-create it with a 'dummy' password, to make it a domain admin. It would be nice if the account of an external user would be editable, just like it is for a local user.

**Comment by akissa** [comment]
This is a design decision, external accounts are not to be used as admin accounts as there is no way at the moment to enforce password strength checks on external accounts. All admin accounts are designed to be local accounts such that the security posture can be set and enforced.

**Comment by rmoesbergen** [comment]
Ok, makes sense. Thanks!
