### ISSUE TITLE
[bug] Quarantine sync (syncthing) via IPV6 doesn't work

### ISSUE THREAD

**Issue by rmoesbergen** [baruwaproject/baruwa2#89]
When trying to configure mailnodes to communicate for shared quarantine over IPv6, I encountered the follow issue:

In the syncthing configuration file, an IPv6 address needs to be surrounded with square brackets ([]). The current code to generate a syncthing config.xml does not take this into account, and so syncing fails (nodes cannot connect / find each other). Also, the GUI does not permit to enter an IP address with square brackets in it (and should not need to, if the underlying code knows about the square brackets)

See also: https://docs.syncthing.net/users/config.html

**Comment by akissa** [comment]
Fixed
