### ISSUE TITLE
[bug] Mailscanner crashes when an org. has an IP subnet in relay settings

### ISSUE THREAD

**Issue by rmoesbergen** [baruwaproject/baruwa2#90]
When I add an entire IP subnet under Organization -> Add relay settings, for example: 10.0.0.0/8, Mailscanner starts crashing:

MailScanner: Process did not exit cleanly, returned 255 with signal 0

I did a manual debug trace when this configuration was active, the logging is as follows:

.....
09:59:50 Jul 20 09:59:50.783 [17819] dbg: dcc: DCC learning not enabled by dcc_learn_score
09:59:50 Jul 20 09:59:50.783 [17819] dbg: check: is spam? score=5.278 required=5
09:59:50 Jul 20 09:59:50.783 [17819] dbg: check: tests=DCC_CHECK,MISSING_DATE,MISSING_HEADERS,MISSING_SUBJECT,NO_RECEIVED,NO_RELAYS
09:59:50 Jul 20 09:59:50.783 [17819] dbg: check: subtests=__BODY_TEXT_LINE,__DKIM_DEPENDABLE,__EMPTY_BODY,__GATED_THROUGH_RCVD_REMOVER,__HAS_FROM,__HAS_MESSAGE_ID,__HAS_MSGID,__KAM_DROPBOX2,__KAM_FAKEDELIVER12,__KAM_FAKEDELIVER4,__KAM_FAKEDELIVER6,__KAM_FAKEDELIVER8,__KAM_GOOGLE2_2,__KAM_HARP3,__KAM_HAS_0_URIS,__KAM_JURY3,__KAM_MULTIPLE_FROM,__KAM_PAYPAL3B,__KAM_UPS2,__KHOP_NO_FULL_NAME,__MISSING_REF,__MISSING_REPLY,__MSGID_OK_DIGITS,__MSGID_OK_HOST,__MSOE_MID_WRONG_CASE,__NONEMPTY_BODY,__NOT_SPOOFED,__SANE_MSGID,__SUBJ_SHORT,__TO_NO_ARROWS_R,__UNUSABLE_MSGID,__ZMISOBER_P_MSGID
09:59:50 Jul 20 09:59:50.784 [17819] dbg: check: tagrun - tag LASTEXTERNALIP is still blocking action 1
09:59:50 Jul 20 09:59:50.784 [17819] dbg: check: tagrun - tag SENDERDOMAIN is still blocking action 0
09:59:50 Jul 20 09:59:50.784 [17819] dbg: check: tagrun - tag DKIMDOMAIN is still blocking action 2
09:59:50 Jul 20 09:59:50.784 [17819] dbg: plugin: Mail::SpamAssassin::Plugin::Bayes=HASH(0x62a7790) implements 'learner_close', priority 0
09:59:50 Jul 20 09:59:50.785 [17819] dbg: plugin: Mail::SpamAssassin::Plugin::TxRep=HASH(0x64e4ff8) implements 'learner_close', priority 0
09:59:50 Jul 20 09:59:50.786 [17819] dbg: TxRep: learner_close
09:59:50 Jul 20 09:59:50.786 [17819] dbg: TxRep: learner_close
09:59:50 Jul 20 09:59:50.786 [17819] dbg: plugin: Mail::SpamAssassin::Plugin::Shortcircuit=HASH(0x629b168) implements 'compile_now_finish', priority 0
09:59:50 Building a message batch to scan...
09:59:50 Have a batch of 11 messages.
**09:59:57 Invalid netblock: 10.255.255.255-42.4.0.0.0.0.0.0.0.0.0.0.0.0.0.0 at /usr/share/MailScanner/MailScanner/Config.pm line 621**
 Failed.

This is quite a nasty one, since we're not able to relay outbound unless we specify every IP separately. Not an option with 1000+ servers.

**Comment by rmoesbergen** [comment]
This seems related: http://lists.mailscanner.info/pipermail/mailscanner/2016-March/103240.html

**Comment by akissa** [comment]
I cannot replicate this, the relay settings are not even used in mailscanner. I think you have input an incorrect value else where.

**Comment by akissa** [comment]
That is matching a ruleset, it is a bug. But it is not caused by the relay settings. I suspect it is from the approved senders or banned senders, i am releasing a fix which should hit the mirrors in a few minutes.

**Comment by rmoesbergen** [comment]
That doesn't make sense to me... When the only change I make is the relay setting and it clearly makes the crash appear / go away, how can it not be the relay settings? Oh well, I'll check if the fix works, please let me know when it's there.

**Comment by akissa** [comment]
The updates have hit the mirrors.

**Comment by rmoesbergen** [comment]
Ok, I tested mailscanner-4.85.5-23.el6.noarch, but it does not fix the crash. Output is slightly different though:

12:05:20 Jul 20 12:05:20.940 [9125] dbg: learn: auto-learn? ham=0.1, spam=12, body-points=0.001, head-points=0.27, learned-points=-2
12:05:20 Jul 20 12:05:20.941 [9125] dbg: learn: auto-learn? no: inside auto-learn thresholds, not considered ham or spam
12:05:20 Jul 20 12:05:20.953 [9125] dbg: netset: cache trusted_networks hits/attempts: 15/16, 93.8 %
12:05:20 SpamAssassin failed with real error: Invalid netblock: 10.255.255.255-38.7.248.176.64.1.12.11.0.0.0.0.0.0.231.36979 at /usr/share/MailScanner/MailScanner/Config.pm line 622
12:05:20  at /usr/share/MailScanner/MailScanner/SA.pm line 1203
 Failed.

The SA.pm is new...

**Comment by akissa** [comment]
Please email us the queue files.

**Comment by akissa** [comment]
Ping ?

**Comment by rmoesbergen** [comment]
I sent them just now.

**Comment by akissa** [comment]
I cannot replicate the issue using those files and a relay setting of 10.0.0.0/8 As previously stated i think you have some other non default configuration causing the issue.

What is the output of

`fgrep -rn '10.0.0' /etc/MailScanner/`

**Comment by rmoesbergen** [comment]
$ fgrep -r '10.0.0' /etc/MailScanner/
/etc/MailScanner/baruwa/rules/highspam.score.rules:From:	10.0.0.0/8	20.0
/etc/MailScanner/baruwa/rules/highspam.actions.rules:From:	10.0.0.0/8	deliver
/etc/MailScanner/baruwa/rules/spam.score.rules:From:	10.0.0.0/8	10.0
/etc/MailScanner/baruwa/rules/spam.actions.rules:From:	10.0.0.0/8	deliver

**Comment by rmoesbergen** [comment]
setting the spamscores to something other than 0.0 is the trick... If I leave those at 0.0, the entries above are not created and things keep working.

**Comment by akissa** [comment]
Got it.

**Comment by akissa** [comment]
It should be fixed now.

**Comment by rmoesbergen** [comment]
Yes, it works now, even with spam scores set! Thanks!
