### ISSUE TITLE
[bug] Dkim selector not correct in web-interface when not using default

### ISSUE THREAD

**Issue by rmoesbergen** [baruwaproject/baruwa2#91]
When not using the default DKIM selector (baruwa), this is not displayed correctly in the web-interface when enabling dkim signing. The web interface displays a sample record, but the dns name is 'baruwa._domainkeys', and not the real DKIM selector.

**Comment by rmoesbergen** [comment]
This probably only happens on servers with only the 'web' role (like we have), because the dkim selector is not configured in baruwa-setup for this role (and remains at the default setting)

**Comment by akissa** [comment]
Fixed
