### ISSUE TITLE
[bug] Can't "deselect" IP-addresses from domain

### ISSUE THREAD

**Issue by lumix1991** [baruwaproject/baruwa2#92]
Hi,

When you select one or more outbound IP-adresses for a domain, you can't "deselect" these anymore. Maybe you need to add a option here that has "- default ip addresses -" or something.

The only way to deselect them are to delete the IP-adresses from the Scanner settings or to use a debugger tool such as FireBug to delete the HTML <option /> elements from the HTML DOM and the submit the form.

![screenshot 2016-08-17 10 21 15](https://cloud.githubusercontent.com/assets/1307710/17729556/0e9a8322-6465-11e6-8faa-98275b0f33bc.png)

**Comment by akissa** [comment]
Press the control button and click the highlighted address.

**Comment by lumix1991** [comment]
Doesn't work in Chrome on OSX (both control and command key). I will test on Windows tomorrow.

**Comment by akissa** [comment]
I cannot replicate this, it is not an issue with the server side code. On a mac i use the cmd key and the mouse pointer to deselect or select on a multi select option box and there are no issues.
