### ISSUE TITLE
[bug] 'From' column empty when using IE11 in the admin interface

### ISSUE THREAD

**Issue by rmoesbergen** [baruwaproject/baruwa2#94]
When viewing the Lists -> Approved Senders or Lists -> Banned Senders with IE11, the 'from' column seems empty (no e-mail adresses are visible). In Firefox or Chrome this seems to work OK.

**Comment by akissa** [comment]
Please provide a screenshot.

**Comment by rmoesbergen** [comment]
![empty-from](https://cloud.githubusercontent.com/assets/8319432/17888463/5127ca18-692b-11e6-8a53-345a55b1d5dd.png)

**Comment by akissa** [comment]
Fixed in latest update please confirm.

**Comment by rmoesbergen** [comment]
Just tested this, but no, still an empty column just like in the screenshot. When I press 'F5', i briefly see the contents, but once page is rendered completely, the column in empty again.

**Comment by akissa** [comment]
I cannot replicate this, is it possible that you are using a theme that you have
not updated ?

**Comment by rmoesbergen** [comment]
We don't have any customizations to the website / theme. Very strange...

**Comment by akissa** [comment]
Can you please provide the HTML code for one of the rows.

**Comment by rmoesbergen** [comment]
Sure:

`		    <tr id="list-id-311">
		        <td class="lists_hash hidden-phone">311</td>
				<td title="info@newsletter.thuisbezorgd.nl" class="lists_from fatfield" style="float: none; position: static;"></td>
		        <td class="lists_to hidden-phone">any</td>
		        <td class="lists_action"><a href="/lists/delete/311"><i class="icon-remove red"></i></a></td>
		    </tr>
`

**Comment by rmoesbergen** [comment]
Guess this can be closed, no-one uses IE11 anymore...
