### ISSUE TITLE
[bug] dmarc-expire fails to expire due to database constraint

### ISSUE THREAD

**Issue by rmoesbergen** [baruwaproject/baruwa2#96]
I get this error when dmarc report generation runs:

baruwa-dmarcexpire: DELETE failed: ERROR: update or delete on table "dmarc_messages" violates foreign key constraint "dmarc_signatures_message_fkey" on table "dmarc_signatures"
DETAIL: Key (id)=(1) is still referenced from table "dmarc_signatures".

**Comment by akissa** [comment]
Fixed
