### ISSUE TITLE
[bug] All outbound e-mail is routed through "dedicated ip-adresses" of other domain.

### ISSUE THREAD

**Issue by lumix1991** [baruwaproject/baruwa2#98]
Hi,

After a long email exchange between me and Baruwa support, I am not succeded in explaining a bug with the "dedicated IP-address" mechanism within Baruwa, Let's try it again, here on Github.

Since BaruwaOS version 6.8 it's possible to dedicate one or more IPs to a specific domain for outbound mail routing;
https://www.baruwa.com/docs/guide/admin/releasenotes/6.8.html#dedicated-ip-addresses

We tried this by assigning 1 extra public IP to every mail node, and assigned these as "Dediated IP adresses" to one single domain of one of our customers so that these outbound mail is seperated from all other oubound mail.

All outbound mail from this domain is routed through these IP's, perfect!

What is not working perfectly, is the following behaviour;

ALL other outbound mail from ALL other domains in Baruwa is routed through these "dedicated IPs" as well! You should expect that this mail is routed through the default IP's of the baruwa nodes instead of the ones that we have assigned to a single domain. But that is not happening. The default IP's (that were used for outbound mail before) are not sending any mail anymore!

Andrew told me that this behaviour is totally right, but then the meaning of "dedicated" is not right here. 

Please fix this issue, so that all mail is sended through the default IP's of the mail nodes, except for the domains that have a dedicated IP assigned.

**Comment by lumix1991** [comment]
Andrew, when will version 3.0 be released?

**Comment by lumix1991** [comment]
I temporarly fixed it (so yes, it is possible) with the following entry under remote_smtp in exim_out.conf:

interface = ${lookup{$sender_address_domain}lsearch{/etc/exim/eximIps.txt}{$value}{my_default_ip}}

in /etc/exim/eximIps.txt i defined the domains and their "dedicated IPs"

**Comment by akissa** [comment]
Your requirement would break the random pool feature, please use assignment if you want to separate traffic between customers

https://www.baruwa.com/docs/guide/admin/releasenotes/6.8.html#mta-random-ip-address-pools

**Comment by lumix1991** [comment]
Too bad that this issue is already closed.

Can you tell me how i can achieve the following situation:

We have around 200 domains in our cluster, for just one domain we want dedicated IPs for outbound mail (because this client sends bulk mail and get us blacklisted sometimes, we don't want that our other customers are affected by this)

That's all.
