### ISSUE TITLE
[bug] Hostkarma 'Yellow' listed domains/ips are incorrectly blocked!

### ISSUE THREAD

**Issue by rmoesbergen** [baruwaproject/baruwa2#99]
The hostkarma blocklist has a 'yellow' listing, which means there is no information being kept for the domain or ip ranges. However: Baruwa seems to reject e-mail when a domain is yellow listed, which is incorrect and causes mail to be lost / non-delivered.

Problem seems to be here, in exim.conf:
hostkarma.junkemailfilter.com=127.0.0.2/<;$sender_host_address;$sender_address_domain : \

A yellow listing returns '127.0.0.3'. Could this be the problem?

**Comment by akissa** [comment]
hostkarma.junkemailfilter.com=127.0.0.2 means the acl only fires if the query returns 127.0.0.2, so there is no why it is blocking yellow listed senders.

**Comment by rmoesbergen** [comment]
Right, I see that not only ip's but also the sending domain is being looked-up, and in this case this is what triggers the blocking. I don't see a 'de-list' request on the hostkarma website for blocked domains (only ips). I think I'll disable this list for now, too unreliable.

**Comment by rmoesbergen** [comment]
Sorry for the noise...
